// <auto-generated>
//     SHA-256 digests of the native runtime files shipped with this package, checked by
//     UsdExporter before the first P/Invoke so a substituted binary fails loudly rather
//     than being loaded and executed in-process.
//
//     Do not edit by hand. Regenerate after every native rebuild:
//         python3 Native~/generate_native_hashes.py
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Unity.USDToolkit.Native
{
    internal static class NativeRuntimeHashes
    {
        // File name -> SHA-256 (lowercase hex). Keyed by name because every shipped
        // binary's name is unique across platforms, so one table covers them all and only
        // the files present on the running platform get compared.
        internal static readonly Dictionary<string, string> Expected =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Runtime/Plugins/x86_64/Windows/UnityUSDToolkitNative.dll
            { "UnityUSDToolkitNative.dll", "bf39fb49a93ddb68e8400eda305fba437266148144a5c501a814ef7d1237858a" },
            // Runtime/Plugins/macOS/UnityUSDToolkitNative.dylib
            { "UnityUSDToolkitNative.dylib", "e65b5e8837778cc65acacdd3492ca35e93b064e0ac455c08ae2aad31d5ae9c7e" },
            // Runtime/Plugins/x86_64/Linux/libUnityUSDToolkitNative.so
            { "libUnityUSDToolkitNative.so", "174665c8a6cba024a1bea3adecd7073958ef1a599d8e6d583ebb9f33b378b77c" },
            // Runtime/Plugins/macOS/libtbb.dylib
            { "libtbb.dylib", "d3aa3199e1989c37823517a9e101ef813ac9c842f196075ed0eb9bb5c524606d" },
            // Runtime/Plugins/x86_64/Linux/lib/libtbb.so.2
            { "libtbb.so.2", "302a86d4e89323500b1758dabc5cd61e15d05a4428fe99d027e1f773214c0651" },
            // Runtime/Plugins/macOS/libtbbmalloc.dylib
            { "libtbbmalloc.dylib", "a6ae12e23c30e62c4a5154dd58e9913f4bf808544d3f6d94341eeb7a5cf35800" },
            // Runtime/Plugins/macOS/libtbbmalloc_proxy.dylib
            { "libtbbmalloc_proxy.dylib", "672edc413a0fdfd7e5fb8ac4afe4f505a3f54ede471cd4aaede94419c8d6ca1f" },
            // Runtime/Plugins/macOS/libusd_ms.dylib
            { "libusd_ms.dylib", "50b5c91f2eb0cb39f5e872772932e653ecaa61f5cff9036163c578b7dce89f0b" },
            // Runtime/Plugins/x86_64/Linux/lib/libusd_ms.so
            { "libusd_ms.so", "2abb6353749d6332de0546774fbf4a4ef25d896b64b0432223d2aadb0accea45" },
            // Runtime/Plugins/x86_64/Windows/tbb.dll
            { "tbb.dll", "692380cecd03181d7fd536e4402783e7f38ea0765b35bb52a3236256959b40cd" },
            // Runtime/Plugins/x86_64/Windows/usd_rt.dll
            { "usd_rt.dll", "ac9108431d026fe32b670fd172fd021cfefc2be9357ee8723cd102ea2a6b7370" },
        };
    }
}
