#!/usr/bin/env python3
"""Regenerates Runtime/Native/NativeRuntimeHashes.g.cs from the shipped native payload.

The managed loader compares every native binary it finds against the digest recorded here
before the first P/Invoke, so a swapped or truncated binary fails loudly instead of being
loaded. Run this after EVERY native rebuild -- the build output is a new binary with a new
digest, and a stale manifest makes the package refuse its own payload.

    python3 Native~/generate_native_hashes.py

The digests live in a generated C# file rather than a data file next to the binaries on
purpose: a manifest shipped beside the payload can be edited by anyone who can edit the
payload, whereas replacing these values means patching a compiled assembly.
"""

import hashlib
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
PAYLOAD = REPO / "Runtime" / "Plugins"
OUTPUT = REPO / "Runtime" / "Native" / "NativeRuntimeHashes.g.cs"


# A Git LFS pointer is a small text file that begins with this line. Hashing one would record
# the pointer's digest instead of the binary's, and the loader would then refuse the real file on
# every machine that has it -- a single-platform rebuild run with an incomplete LFS working copy
# would silently break the other two platforms. Refuse instead of guessing.
LFS_POINTER_PREFIX = b"version https://git-lfs.github.com/spec/"


def is_lfs_pointer(path: pathlib.Path) -> bool:
    # Pointers are a few hundred bytes; a real binary never is.
    if path.stat().st_size > 1024:
        return False

    with path.open("rb") as handle:
        return handle.read(len(LFS_POINTER_PREFIX)) == LFS_POINTER_PREFIX


def is_native_binary(path: pathlib.Path) -> bool:
    if path.suffix == ".meta":
        return False
    if path.suffix in (".dll", ".dylib", ".so"):
        return True
    # libtbb.so.2 and friends: a version suffix after .so
    return ".so." in path.name


def main() -> int:
    if not PAYLOAD.is_dir():
        print(f"error: no payload directory at {PAYLOAD}", file=sys.stderr)
        return 1

    candidates = [
        path for path in sorted(PAYLOAD.rglob("*"))
        if path.is_file() and is_native_binary(path)
    ]

    pointers = [path for path in candidates if is_lfs_pointer(path)]
    if pointers:
        print(
            "error: these payload files are Git LFS pointers, not real binaries:",
            file=sys.stderr,
        )
        for path in pointers:
            print(f"  {path.relative_to(REPO)}", file=sys.stderr)
        print(
            "\nThe manifest covers every platform, not just the one you rebuilt, so writing it\n"
            "now would record the pointers' digests and break those platforms at load time.\n"
            "Fetch the real content first:\n"
            "    git lfs install && git lfs pull\n"
            "then re-run this script.",
            file=sys.stderr,
        )
        return 1

    digests = {}
    for path in candidates:
        name = path.name
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        previous = digests.get(name)
        if previous is not None and previous[0] != digest:
            # Keyed by file name, so two different files sharing one name would make the
            # manifest ambiguous. All current payload names are unique across platforms.
            print(
                f"error: '{name}' appears twice with different contents "
                f"({previous[1]} and {path.relative_to(REPO)})",
                file=sys.stderr,
            )
            return 1

        digests[name] = (digest, path.relative_to(REPO))

    if not digests:
        print(f"error: found no native binaries under {PAYLOAD}", file=sys.stderr)
        return 1

    lines = [
        "// <auto-generated>",
        "//     SHA-256 digests of the native runtime files shipped with this package, checked by",
        "//     UsdExporter before the first P/Invoke so a substituted binary fails loudly rather",
        "//     than being loaded and executed in-process.",
        "//",
        "//     Do not edit by hand. Regenerate after every native rebuild:",
        "//         python3 Native~/generate_native_hashes.py",
        "// </auto-generated>",
        "",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace Unity.USDToolkit.Native",
        "{",
        "    internal static class NativeRuntimeHashes",
        "    {",
        "        // File name -> SHA-256 (lowercase hex). Keyed by name because every shipped",
        "        // binary's name is unique across platforms, so one table covers them all and only",
        "        // the files present on the running platform get compared.",
        "        internal static readonly Dictionary<string, string> Expected =",
        "            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)",
        "        {",
    ]

    for name in sorted(digests):
        digest, relative = digests[name]
        lines.append(f'            // {relative.as_posix()}')
        lines.append(f'            {{ "{name}", "{digest}" }},')

    lines += [
        "        };",
        "    }",
        "}",
        "",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} with {len(digests)} digest(s):")
    for name in sorted(digests):
        print(f"  {digests[name][0]}  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
